/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsTrainingRouteImport } from './routes/solutions/training'
import { Route as SolutionsSupportRouteImport } from './routes/solutions/support'
import { Route as SolutionsItsmRouteImport } from './routes/solutions/itsm'
import { Route as SolutionsIntegrationRouteImport } from './routes/solutions/integration'
import { Route as SolutionsCloudMigrationRouteImport } from './routes/solutions/cloud-migration'
import { Route as SolutionsAdvisoryRouteImport } from './routes/solutions/advisory'
import { Route as MarketplaceAppsTimerRouteImport } from './routes/marketplace-apps/timer'
import { Route as MarketplaceAppsTimeSheetRouteImport } from './routes/marketplace-apps/time-sheet'
import { Route as MarketplaceAppsIssueTemplateRouteImport } from './routes/marketplace-apps/issue-template'
import { Route as MarketplaceAppsChecklistRouteImport } from './routes/marketplace-apps/checklist'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTrainingRoute = SolutionsTrainingRouteImport.update({
  id: '/solutions/training',
  path: '/solutions/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSupportRoute = SolutionsSupportRouteImport.update({
  id: '/solutions/support',
  path: '/solutions/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsItsmRoute = SolutionsItsmRouteImport.update({
  id: '/solutions/itsm',
  path: '/solutions/itsm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIntegrationRoute = SolutionsIntegrationRouteImport.update({
  id: '/solutions/integration',
  path: '/solutions/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCloudMigrationRoute = SolutionsCloudMigrationRouteImport.update({
  id: '/solutions/cloud-migration',
  path: '/solutions/cloud-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAdvisoryRoute = SolutionsAdvisoryRouteImport.update({
  id: '/solutions/advisory',
  path: '/solutions/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAppsTimerRoute = MarketplaceAppsTimerRouteImport.update({
  id: '/marketplace-apps/timer',
  path: '/marketplace-apps/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAppsTimeSheetRoute =
  MarketplaceAppsTimeSheetRouteImport.update({
    id: '/marketplace-apps/time-sheet',
    path: '/marketplace-apps/time-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceAppsIssueTemplateRoute =
  MarketplaceAppsIssueTemplateRouteImport.update({
    id: '/marketplace-apps/issue-template',
    path: '/marketplace-apps/issue-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceAppsChecklistRoute =
  MarketplaceAppsChecklistRouteImport.update({
    id: '/marketplace-apps/checklist',
    path: '/marketplace-apps/checklist',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/marketplace-apps/checklist': typeof MarketplaceAppsChecklistRoute
  '/marketplace-apps/issue-template': typeof MarketplaceAppsIssueTemplateRoute
  '/marketplace-apps/time-sheet': typeof MarketplaceAppsTimeSheetRoute
  '/marketplace-apps/timer': typeof MarketplaceAppsTimerRoute
  '/solutions/advisory': typeof SolutionsAdvisoryRoute
  '/solutions/cloud-migration': typeof SolutionsCloudMigrationRoute
  '/solutions/integration': typeof SolutionsIntegrationRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/support': typeof SolutionsSupportRoute
  '/solutions/training': typeof SolutionsTrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/marketplace-apps/checklist': typeof MarketplaceAppsChecklistRoute
  '/marketplace-apps/issue-template': typeof MarketplaceAppsIssueTemplateRoute
  '/marketplace-apps/time-sheet': typeof MarketplaceAppsTimeSheetRoute
  '/marketplace-apps/timer': typeof MarketplaceAppsTimerRoute
  '/solutions/advisory': typeof SolutionsAdvisoryRoute
  '/solutions/cloud-migration': typeof SolutionsCloudMigrationRoute
  '/solutions/integration': typeof SolutionsIntegrationRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/support': typeof SolutionsSupportRoute
  '/solutions/training': typeof SolutionsTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/marketplace-apps/checklist': typeof MarketplaceAppsChecklistRoute
  '/marketplace-apps/issue-template': typeof MarketplaceAppsIssueTemplateRoute
  '/marketplace-apps/time-sheet': typeof MarketplaceAppsTimeSheetRoute
  '/marketplace-apps/timer': typeof MarketplaceAppsTimerRoute
  '/solutions/advisory': typeof SolutionsAdvisoryRoute
  '/solutions/cloud-migration': typeof SolutionsCloudMigrationRoute
  '/solutions/integration': typeof SolutionsIntegrationRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/support': typeof SolutionsSupportRoute
  '/solutions/training': typeof SolutionsTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/marketplace-apps/checklist'
    | '/marketplace-apps/issue-template'
    | '/marketplace-apps/time-sheet'
    | '/marketplace-apps/timer'
    | '/solutions/advisory'
    | '/solutions/cloud-migration'
    | '/solutions/integration'
    | '/solutions/itsm'
    | '/solutions/support'
    | '/solutions/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/marketplace-apps/checklist'
    | '/marketplace-apps/issue-template'
    | '/marketplace-apps/time-sheet'
    | '/marketplace-apps/timer'
    | '/solutions/advisory'
    | '/solutions/cloud-migration'
    | '/solutions/integration'
    | '/solutions/itsm'
    | '/solutions/support'
    | '/solutions/training'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/marketplace-apps/checklist'
    | '/marketplace-apps/issue-template'
    | '/marketplace-apps/time-sheet'
    | '/marketplace-apps/timer'
    | '/solutions/advisory'
    | '/solutions/cloud-migration'
    | '/solutions/integration'
    | '/solutions/itsm'
    | '/solutions/support'
    | '/solutions/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  MarketplaceAppsChecklistRoute: typeof MarketplaceAppsChecklistRoute
  MarketplaceAppsIssueTemplateRoute: typeof MarketplaceAppsIssueTemplateRoute
  MarketplaceAppsTimeSheetRoute: typeof MarketplaceAppsTimeSheetRoute
  MarketplaceAppsTimerRoute: typeof MarketplaceAppsTimerRoute
  SolutionsAdvisoryRoute: typeof SolutionsAdvisoryRoute
  SolutionsCloudMigrationRoute: typeof SolutionsCloudMigrationRoute
  SolutionsIntegrationRoute: typeof SolutionsIntegrationRoute
  SolutionsItsmRoute: typeof SolutionsItsmRoute
  SolutionsSupportRoute: typeof SolutionsSupportRoute
  SolutionsTrainingRoute: typeof SolutionsTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/training': {
      id: '/solutions/training'
      path: '/solutions/training'
      fullPath: '/solutions/training'
      preLoaderRoute: typeof SolutionsTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/support': {
      id: '/solutions/support'
      path: '/solutions/support'
      fullPath: '/solutions/support'
      preLoaderRoute: typeof SolutionsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/itsm': {
      id: '/solutions/itsm'
      path: '/solutions/itsm'
      fullPath: '/solutions/itsm'
      preLoaderRoute: typeof SolutionsItsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/integration': {
      id: '/solutions/integration'
      path: '/solutions/integration'
      fullPath: '/solutions/integration'
      preLoaderRoute: typeof SolutionsIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cloud-migration': {
      id: '/solutions/cloud-migration'
      path: '/solutions/cloud-migration'
      fullPath: '/solutions/cloud-migration'
      preLoaderRoute: typeof SolutionsCloudMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/advisory': {
      id: '/solutions/advisory'
      path: '/solutions/advisory'
      fullPath: '/solutions/advisory'
      preLoaderRoute: typeof SolutionsAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/timer': {
      id: '/marketplace-apps/timer'
      path: '/marketplace-apps/timer'
      fullPath: '/marketplace-apps/timer'
      preLoaderRoute: typeof MarketplaceAppsTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/time-sheet': {
      id: '/marketplace-apps/time-sheet'
      path: '/marketplace-apps/time-sheet'
      fullPath: '/marketplace-apps/time-sheet'
      preLoaderRoute: typeof MarketplaceAppsTimeSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/issue-template': {
      id: '/marketplace-apps/issue-template'
      path: '/marketplace-apps/issue-template'
      fullPath: '/marketplace-apps/issue-template'
      preLoaderRoute: typeof MarketplaceAppsIssueTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/checklist': {
      id: '/marketplace-apps/checklist'
      path: '/marketplace-apps/checklist'
      fullPath: '/marketplace-apps/checklist'
      preLoaderRoute: typeof MarketplaceAppsChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  MarketplaceAppsChecklistRoute: MarketplaceAppsChecklistRoute,
  MarketplaceAppsIssueTemplateRoute: MarketplaceAppsIssueTemplateRoute,
  MarketplaceAppsTimeSheetRoute: MarketplaceAppsTimeSheetRoute,
  MarketplaceAppsTimerRoute: MarketplaceAppsTimerRoute,
  SolutionsAdvisoryRoute: SolutionsAdvisoryRoute,
  SolutionsCloudMigrationRoute: SolutionsCloudMigrationRoute,
  SolutionsIntegrationRoute: SolutionsIntegrationRoute,
  SolutionsItsmRoute: SolutionsItsmRoute,
  SolutionsSupportRoute: SolutionsSupportRoute,
  SolutionsTrainingRoute: SolutionsTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
