/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as SolutionsTrainingRouteImport } from './routes/solutions/training'
import { Route as SolutionsSupportRouteImport } from './routes/solutions/support'
import { Route as SolutionsRovoRouteImport } from './routes/solutions/rovo'
import { Route as SolutionsJiraAlignRouteImport } from './routes/solutions/jira-align'
import { Route as SolutionsItsmRouteImport } from './routes/solutions/itsm'
import { Route as SolutionsIntegrationRouteImport } from './routes/solutions/integration'
import { Route as SolutionsCloudMigrationRouteImport } from './routes/solutions/cloud-migration'
import { Route as SolutionsAdvisoryRouteImport } from './routes/solutions/advisory'
import { Route as MarketplaceAppsTimerRouteImport } from './routes/marketplace-apps/timer'
import { Route as MarketplaceAppsTimeSheetRouteImport } from './routes/marketplace-apps/time-sheet'
import { Route as MarketplaceAppsIssueTemplateRouteImport } from './routes/marketplace-apps/issue-template'
import { Route as MarketplaceAppsChecklistRouteImport } from './routes/marketplace-apps/checklist'

const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTrainingRoute = SolutionsTrainingRouteImport.update({
  id: '/solutions/training',
  path: '/solutions/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSupportRoute = SolutionsSupportRouteImport.update({
  id: '/solutions/support',
  path: '/solutions/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRovoRoute = SolutionsRovoRouteImport.update({
  id: '/solutions/rovo',
  path: '/solutions/rovo',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsJiraAlignRoute = SolutionsJiraAlignRouteImport.update({
  id: '/solutions/jira-align',
  path: '/solutions/jira-align',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsItsmRoute = SolutionsItsmRouteImport.update({
  id: '/solutions/itsm',
  path: '/solutions/itsm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIntegrationRoute = SolutionsIntegrationRouteImport.update({
  id: '/solutions/integration',
  path: '/solutions/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCloudMigrationRoute = SolutionsCloudMigrationRouteImport.update({
  id: '/solutions/cloud-migration',
  path: '/solutions/cloud-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAdvisoryRoute = SolutionsAdvisoryRouteImport.update({
  id: '/solutions/advisory',
  path: '/solutions/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAppsTimerRoute = MarketplaceAppsTimerRouteImport.update({
  id: '/marketplace-apps/timer',
  path: '/marketplace-apps/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAppsTimeSheetRoute =
  MarketplaceAppsTimeSheetRouteImport.update({
    id: '/marketplace-apps/time-sheet',
    path: '/marketplace-apps/time-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceAppsIssueTemplateRoute =
  MarketplaceAppsIssueTemplateRouteImport.update({
    id: '/marketplace-apps/issue-template',
    path: '/marketplace-apps/issue-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceAppsChecklistRoute =
  MarketplaceAppsChecklistRouteImport.update({
    id: '/marketplace-apps/checklist',
    path: '/marketplace-apps/checklist',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/marketplace-apps/checklist': typeof MarketplaceAppsChecklistRoute
  '/marketplace-apps/issue-template': typeof MarketplaceAppsIssueTemplateRoute
  '/marketplace-apps/time-sheet': typeof MarketplaceAppsTimeSheetRoute
  '/marketplace-apps/timer': typeof MarketplaceAppsTimerRoute
  '/solutions/advisory': typeof SolutionsAdvisoryRoute
  '/solutions/cloud-migration': typeof SolutionsCloudMigrationRoute
  '/solutions/integration': typeof SolutionsIntegrationRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/jira-align': typeof SolutionsJiraAlignRoute
  '/solutions/rovo': typeof SolutionsRovoRoute
  '/solutions/support': typeof SolutionsSupportRoute
  '/solutions/training': typeof SolutionsTrainingRoute
  '/about-us': typeof AboutUsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/marketplace-apps/checklist': typeof MarketplaceAppsChecklistRoute
  '/marketplace-apps/issue-template': typeof MarketplaceAppsIssueTemplateRoute
  '/marketplace-apps/time-sheet': typeof MarketplaceAppsTimeSheetRoute
  '/marketplace-apps/timer': typeof MarketplaceAppsTimerRoute
  '/solutions/advisory': typeof SolutionsAdvisoryRoute
  '/solutions/cloud-migration': typeof SolutionsCloudMigrationRoute
  '/solutions/integration': typeof SolutionsIntegrationRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/jira-align': typeof SolutionsJiraAlignRoute
  '/solutions/rovo': typeof SolutionsRovoRoute
  '/solutions/support': typeof SolutionsSupportRoute
  '/solutions/training': typeof SolutionsTrainingRoute
  '/about-us': typeof AboutUsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/marketplace-apps/checklist': typeof MarketplaceAppsChecklistRoute
  '/marketplace-apps/issue-template': typeof MarketplaceAppsIssueTemplateRoute
  '/marketplace-apps/time-sheet': typeof MarketplaceAppsTimeSheetRoute
  '/marketplace-apps/timer': typeof MarketplaceAppsTimerRoute
  '/solutions/advisory': typeof SolutionsAdvisoryRoute
  '/solutions/cloud-migration': typeof SolutionsCloudMigrationRoute
  '/solutions/integration': typeof SolutionsIntegrationRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/jira-align': typeof SolutionsJiraAlignRoute
  '/solutions/rovo': typeof SolutionsRovoRoute
  '/solutions/support': typeof SolutionsSupportRoute
  '/solutions/training': typeof SolutionsTrainingRoute
  '/about-us/': typeof AboutUsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/marketplace-apps/checklist'
    | '/marketplace-apps/issue-template'
    | '/marketplace-apps/time-sheet'
    | '/marketplace-apps/timer'
    | '/solutions/advisory'
    | '/solutions/cloud-migration'
    | '/solutions/integration'
    | '/solutions/itsm'
    | '/solutions/jira-align'
    | '/solutions/rovo'
    | '/solutions/support'
    | '/solutions/training'
    | '/about-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/marketplace-apps/checklist'
    | '/marketplace-apps/issue-template'
    | '/marketplace-apps/time-sheet'
    | '/marketplace-apps/timer'
    | '/solutions/advisory'
    | '/solutions/cloud-migration'
    | '/solutions/integration'
    | '/solutions/itsm'
    | '/solutions/jira-align'
    | '/solutions/rovo'
    | '/solutions/support'
    | '/solutions/training'
    | '/about-us'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/marketplace-apps/checklist'
    | '/marketplace-apps/issue-template'
    | '/marketplace-apps/time-sheet'
    | '/marketplace-apps/timer'
    | '/solutions/advisory'
    | '/solutions/cloud-migration'
    | '/solutions/integration'
    | '/solutions/itsm'
    | '/solutions/jira-align'
    | '/solutions/rovo'
    | '/solutions/support'
    | '/solutions/training'
    | '/about-us/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  MarketplaceAppsChecklistRoute: typeof MarketplaceAppsChecklistRoute
  MarketplaceAppsIssueTemplateRoute: typeof MarketplaceAppsIssueTemplateRoute
  MarketplaceAppsTimeSheetRoute: typeof MarketplaceAppsTimeSheetRoute
  MarketplaceAppsTimerRoute: typeof MarketplaceAppsTimerRoute
  SolutionsAdvisoryRoute: typeof SolutionsAdvisoryRoute
  SolutionsCloudMigrationRoute: typeof SolutionsCloudMigrationRoute
  SolutionsIntegrationRoute: typeof SolutionsIntegrationRoute
  SolutionsItsmRoute: typeof SolutionsItsmRoute
  SolutionsJiraAlignRoute: typeof SolutionsJiraAlignRoute
  SolutionsRovoRoute: typeof SolutionsRovoRoute
  SolutionsSupportRoute: typeof SolutionsSupportRoute
  SolutionsTrainingRoute: typeof SolutionsTrainingRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/training': {
      id: '/solutions/training'
      path: '/solutions/training'
      fullPath: '/solutions/training'
      preLoaderRoute: typeof SolutionsTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/support': {
      id: '/solutions/support'
      path: '/solutions/support'
      fullPath: '/solutions/support'
      preLoaderRoute: typeof SolutionsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/rovo': {
      id: '/solutions/rovo'
      path: '/solutions/rovo'
      fullPath: '/solutions/rovo'
      preLoaderRoute: typeof SolutionsRovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/jira-align': {
      id: '/solutions/jira-align'
      path: '/solutions/jira-align'
      fullPath: '/solutions/jira-align'
      preLoaderRoute: typeof SolutionsJiraAlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/itsm': {
      id: '/solutions/itsm'
      path: '/solutions/itsm'
      fullPath: '/solutions/itsm'
      preLoaderRoute: typeof SolutionsItsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/integration': {
      id: '/solutions/integration'
      path: '/solutions/integration'
      fullPath: '/solutions/integration'
      preLoaderRoute: typeof SolutionsIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cloud-migration': {
      id: '/solutions/cloud-migration'
      path: '/solutions/cloud-migration'
      fullPath: '/solutions/cloud-migration'
      preLoaderRoute: typeof SolutionsCloudMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/advisory': {
      id: '/solutions/advisory'
      path: '/solutions/advisory'
      fullPath: '/solutions/advisory'
      preLoaderRoute: typeof SolutionsAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/timer': {
      id: '/marketplace-apps/timer'
      path: '/marketplace-apps/timer'
      fullPath: '/marketplace-apps/timer'
      preLoaderRoute: typeof MarketplaceAppsTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/time-sheet': {
      id: '/marketplace-apps/time-sheet'
      path: '/marketplace-apps/time-sheet'
      fullPath: '/marketplace-apps/time-sheet'
      preLoaderRoute: typeof MarketplaceAppsTimeSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/issue-template': {
      id: '/marketplace-apps/issue-template'
      path: '/marketplace-apps/issue-template'
      fullPath: '/marketplace-apps/issue-template'
      preLoaderRoute: typeof MarketplaceAppsIssueTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-apps/checklist': {
      id: '/marketplace-apps/checklist'
      path: '/marketplace-apps/checklist'
      fullPath: '/marketplace-apps/checklist'
      preLoaderRoute: typeof MarketplaceAppsChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  MarketplaceAppsChecklistRoute: MarketplaceAppsChecklistRoute,
  MarketplaceAppsIssueTemplateRoute: MarketplaceAppsIssueTemplateRoute,
  MarketplaceAppsTimeSheetRoute: MarketplaceAppsTimeSheetRoute,
  MarketplaceAppsTimerRoute: MarketplaceAppsTimerRoute,
  SolutionsAdvisoryRoute: SolutionsAdvisoryRoute,
  SolutionsCloudMigrationRoute: SolutionsCloudMigrationRoute,
  SolutionsIntegrationRoute: SolutionsIntegrationRoute,
  SolutionsItsmRoute: SolutionsItsmRoute,
  SolutionsJiraAlignRoute: SolutionsJiraAlignRoute,
  SolutionsRovoRoute: SolutionsRovoRoute,
  SolutionsSupportRoute: SolutionsSupportRoute,
  SolutionsTrainingRoute: SolutionsTrainingRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
